// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3_olmE_EA7KJ9K3yaw86b7B4ml1vD84Q',
    appId: '1:606477394437:android:d2237ea0b06036981bb26c',
    messagingSenderId: '606477394437',
    projectId: 'dryfruit-45af8',
    databaseURL: 'https://dryfruit-45af8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dryfruit-45af8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsv_lfUtSH7s656kEo1A2wAdlI1cHnj54',
    appId: '1:606477394437:ios:2c4bb9b6f89800241bb26c',
    messagingSenderId: '606477394437',
    projectId: 'dryfruit-45af8',
    databaseURL: 'https://dryfruit-45af8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dryfruit-45af8.appspot.com',
    iosClientId: '606477394437-caluf94u53fpkpsju95pekcgf1erjssh.apps.googleusercontent.com',
    iosBundleId: 'com.dfd.dfd',
  );
}
